s/d_1_A_Duplex.html/1_d_A_Duplex.html/g
s/d_2_A_Duplex.html/2_d_A_Duplex.html/g
s/d_3_A_Duplex.html/3_d_A_Duplex.html/g
s/d_4_A_Duplex.html/4_d_A_Duplex.html/g
s/d_5_A_Duplex.html/4_d_A_Duplex.html/g
s/d_6_A_Duplex.html/4_d_A_Duplex.html/g
s/d_7_A_Duplex.html/5_d_A_Duplex.html/g
s/d_8_A_Duplex.html/5_d_A_Duplex.html/g
s/d_9_A_Duplex.html/5_d_A_Duplex.html/g
s/d_10_A_Duplex.html/5_d_A_Duplex.html/g
s/d_11_A_Duplex.html/5_d_A_Duplex.html/g
s/d_12_A_Duplex.html/5_d_A_Duplex.html/g
s/d_13_A_Duplex.html/6_d_A_Duplex.html/g
s/d_14_A_Duplex.html/6_d_A_Duplex.html/g
s/d_15_A_Duplex.html/7_d_A_Duplex.html/g
s/d_16_A_Duplex.html/8_d_A_Duplex.html/g
s/d_17_A_Duplex.html/8_d_A_Duplex.html/g
s/d_18_A_Duplex.html/9_d_A_Duplex.html/g
s/d_19_A_Duplex.html/9_d_A_Duplex.html/g
s/d_20_A_Duplex.html/9_d_A_Duplex.html/g
s/d_21_A_Duplex.html/10_d_A_Duplex.html/g
s/d_22_A_Duplex.html/11_d_A_Duplex.html/g
s/d_23_A_Duplex.html/12_d_A_Duplex.html/g
s/d_24_A_Duplex.html/12_d_A_Duplex.html/g
s/d_25_A_Duplex.html/13_d_A_Duplex.html/g
s/d_26_A_Duplex.html/13_d_A_Duplex.html/g
s/d_27_A_Duplex.html/14_d_A_Duplex.html/g
s/d_28_A_Duplex.html/15_d_A_Duplex.html/g
s/d_29_A_Duplex.html/16_d_A_Duplex.html/g
s/d_30_A_Duplex.html/16_d_A_Duplex.html/g
s/d_31_A_Duplex.html/17_d_A_Duplex.html/g
s/d_32_A_Duplex.html/17_d_A_Duplex.html/g
s/d_33_A_Duplex.html/18_d_A_Duplex.html/g
s/d_34_A_Duplex.html/18_d_A_Duplex.html/g
s/d_35_A_Duplex.html/19_d_A_Duplex.html/g
s/d_36_A_Duplex.html/19_d_A_Duplex.html/g
s/d_37_A_Duplex.html/20_d_A_Duplex.html/g
s/d_38_A_Duplex.html/21_d_A_Duplex.html/g
s/d_39_A_Duplex.html/22_d_A_Duplex.html/g
s/d_40_A_Duplex.html/23_d_A_Duplex.html/g
s/d_41_A_Duplex.html/24_d_A_Duplex.html/g
s/d_42_A_Duplex.html/25_d_A_Duplex.html/g
s/d_43_A_Duplex.html/26_d_A_Duplex.html/g
s/d_44_A_Duplex.html/27_d_A_Duplex.html/g
s/d_45_A_Duplex.html/28_d_A_Duplex.html/g
s/d_46_A_Duplex.html/28_d_A_Duplex.html/g
s/d_47_A_Duplex.html/28_d_A_Duplex.html/g
s/d_48_A_Duplex.html/29_d_A_Duplex.html/g
s/d_49_A_Duplex.html/30_d_A_Duplex.html/g
s/d_50_A_Duplex.html/31_d_A_Duplex.html/g
s/d_51_A_Duplex.html/31_d_A_Duplex.html/g
s/d_52_A_Duplex.html/31_d_A_Duplex.html/g
s/d_53_A_Duplex.html/32_d_A_Duplex.html/g
s/d_54_A_Duplex.html/32_d_A_Duplex.html/g
s/d_55_A_Duplex.html/32_d_A_Duplex.html/g
