s/d_1_A_stick.html/1_d_A_stick.html/g
s/d_2_A_stick.html/1_d_A_stick.html/g
s/d_3_A_stick.html/2_d_A_stick.html/g
s/d_4_A_stick.html/2_d_A_stick.html/g
s/d_5_A_stick.html/2_d_A_stick.html/g
s/d_6_A_stick.html/3_d_A_stick.html/g
s/d_7_A_stick.html/3_d_A_stick.html/g
s/d_8_A_stick.html/3_d_A_stick.html/g
s/d_9_A_stick.html/4_d_A_stick.html/g
s/d_10_A_stick.html/4_d_A_stick.html/g
s/d_11_A_stick.html/4_d_A_stick.html/g
s/d_12_A_stick.html/5_d_A_stick.html/g
