s/d_1_A_Major_case.html/1_d_A_Major_case.html/g
s/d_2_A_Major_case.html/1_d_A_Major_case.html/g
s/d_3_A_Major_case.html/1_d_A_Major_case.html/g
s/d_4_A_Major_case.html/1_d_A_Major_case.html/g
s/d_5_A_Major_case.html/2_d_A_Major_case.html/g
s/d_6_A_Major_case.html/3_d_A_Major_case.html/g
s/d_7_A_Major_case.html/4_d_A_Major_case.html/g
s/d_8_A_Major_case.html/5_d_A_Major_case.html/g
s/d_9_A_Major_case.html/6_d_A_Major_case.html/g
s/d_10_A_Major_case.html/6_d_A_Major_case.html/g
s/d_11_A_Major_case.html/6_d_A_Major_case.html/g
s/d_12_A_Major_case.html/7_d_A_Major_case.html/g
s/d_13_A_Major_case.html/8_d_A_Major_case.html/g
s/d_14_A_Major_case.html/9_d_A_Major_case.html/g
s/d_15_A_Major_case.html/10_d_A_Major_case.html/g
s/d_16_A_Major_case.html/11_d_A_Major_case.html/g
s/d_17_A_Major_case.html/11_d_A_Major_case.html/g
s/d_18_A_Major_case.html/11_d_A_Major_case.html/g
s/d_19_A_Major_case.html/11_d_A_Major_case.html/g
s/d_20_A_Major_case.html/11_d_A_Major_case.html/g
s/d_21_A_Major_case.html/11_d_A_Major_case.html/g
s/d_22_A_Major_case.html/12_d_A_Major_case.html/g
s/d_23_A_Major_case.html/13_d_A_Major_case.html/g
s/d_24_A_Major_case.html/14_d_A_Major_case.html/g
s/d_25_A_Major_case.html/15_d_A_Major_case.html/g
s/d_26_A_Major_case.html/15_d_A_Major_case.html/g
s/d_27_A_Major_case.html/15_d_A_Major_case.html/g
s/d_28_A_Major_case.html/16_d_A_Major_case.html/g
s/d_29_A_Major_case.html/17_d_A_Major_case.html/g
s/d_30_A_Major_case.html/18_d_A_Major_case.html/g
s/d_31_A_Major_case.html/18_d_A_Major_case.html/g
s/d_32_A_Major_case.html/19_d_A_Major_case.html/g
s/d_33_A_Major_case.html/20_d_A_Major_case.html/g
s/d_34_A_Major_case.html/21_d_A_Major_case.html/g
s/d_35_A_Major_case.html/22_d_A_Major_case.html/g
s/d_36_A_Major_case.html/23_d_A_Major_case.html/g
s/d_37_A_Major_case.html/24_d_A_Major_case.html/g
s/d_38_A_Major_case.html/25_d_A_Major_case.html/g
s/d_39_A_Major_case.html/26_d_A_Major_case.html/g
s/d_40_A_Major_case.html/27_d_A_Major_case.html/g
s/d_41_A_Major_case.html/28_d_A_Major_case.html/g
s/d_42_A_Major_case.html/29_d_A_Major_case.html/g
s/d_43_A_Major_case.html/30_d_A_Major_case.html/g
s/d_44_A_Major_case.html/31_d_A_Major_case.html/g
